sudo: required

language: node_js
node_js:
  - stable

services:
  - mongodb

install:
- npm install

script:
- npm run lint
- node scripts/initTests
- npm run coverage
- npm run build

notifications:
    slack: travis-projet:qqijRoPDFiJL99vloreIeAUF